ARG ROS_DISTRO=kilted
FROM osrf/ros:${ROS_DISTRO}-desktop-full

ARG USERID=1000
ARG USER=admin
ARG ROS_DISTRO

######################
# 1) Environment
######################
ENV TERM=linux
ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

######################
# 2) Install
######################
COPY docker/requirements.txt .
RUN apt-get update && apt-get install --no-install-recommends -y $(cat requirements.txt) && rm requirements.txt

RUN sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
RUN wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
RUN apt-get update && apt-get install --no-install-recommends -y gz-ionic

######################
# 3) User
######################
RUN if id -u "$USER" >/dev/null 2>&1; then \
        usermod --uid "$USERID" "$USER"; \
    else \
        EXISTING_USER="$(getent passwd "$USERID" | cut -d: -f1 || true)"; \
        if [ -n "$EXISTING_USER" ]; then \
            usermod -l "$USER" "$EXISTING_USER"; \
            usermod -d "/home/$USER" -m "$USER"; \
        else \
            adduser --uid "$USERID" --gecos "admin" --disabled-password "$USER"; \
        fi; \
    fi \
    && usermod -a -G sudo,dialout,plugdev "$USER" \
    && (grep -qxF '%sudo ALL=(ALL) NOPASSWD:ALL' /etc/sudoers || echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers)
USER $USER

######################
# 4) Update
######################
RUN sudo apt-get update && sudo apt-get upgrade -y && rosdep update

#####################################
# ROS2 dependencies built from source
#####################################


RUN mkdir -p /home/$USER/ros_ws/src
WORKDIR /home/$USER/ros_ws/src
# Clone andino_gz
# RUN git clone --no-checkout https://github.com/Ekumen-OS/andino_gz.git . \
#     && git checkout b3d780631db953c33253e9a6a871bfe3f70c1884 \
#     && rm -rf .git
# RUN git clone https://github.com/Ekumen-OS/andino_gz.git -b kilted
# RUN cd andino_gz && git checkout b3d780631db953c33253e9a6a871bfe3f70c1884

RUN git clone https://github.com/open-rmf/rmf_demos.git -b kilted
RUN git clone https://github.com/orka375/eta_rmf.git

WORKDIR /home/$USER/ros_ws




RUN . /opt/ros/kilted/setup.sh && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release


######################
# Bashrc configuration
######################

# Adds to bashrc the ros kilted overlay sourcing.
RUN echo "source /opt/ros/kilted/setup.bash" >> /home/$USER/.bashrc
RUN echo "source /home/$USER/ros_ws/install/setup.bash" >> /home/$USER/.bashrc
# Adds colcon autocomplete
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /home/$USER/.bashrc
RUN echo "export ROS_DOMAIN_ID=1" >> /home/$USER/.bashrc

#########################
# Pip installation setup
#########################
RUN sudo pip install nudged \
    transforms3d \
    psycopg2 \
    pyqt5 \
    --break-system-packages

#########################
# Workspace configuration
#########################


WORKDIR /home/$USER/ros_ws

CMD ["/bin/bash"]
